import Head from 'next/head'

import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h1>
        Welcome to <a href='https://nextjs.org'>Next.js!</a>
      </h1>
    </div>
  )
}

export default Home
